### ISSUE TITLE
webpack for modern front-end asset management?

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/av-dashboard#12]
investigate using webpack to manage the front end assets

**Comment by mtc2013** [comment]
https://github.com/JDeuce/python-jinja2-webpack

**Comment by mtc2013** [comment]
partially done with webpack in there now

**Comment by mattwr18** [comment]
Needs hash for caching, which is not turned on by default, but is in the documentation

**Comment by FedericoEsparza** [comment]
We might go ahead and close this, because we're creating a frontend repo
