### ISSUE TITLE
Add more useful issue labels

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/av-dashboard#29]
Add more useful issue labels, like `documentation`, `tests`, `devops`.
 
Maybe turn on WaffleBot, so that we have labels with corresponding Waffle columns and more automated issue column moves.

**Comment by FedericoEsparza** [comment]
Add here: https://github.com/AgileVentures/av-dashboard/labels

**Comment by FedericoEsparza** [comment]
`chore` and `project management` would also be useful github/waffle labels.

**Comment by FedericoEsparza** [comment]
`frontend` and `backend` too.

**Comment by brotich** [comment]
![image](https://user-images.githubusercontent.com/23168146/50005016-e9b84380-ffb9-11e8-9e96-6babe33fc2eb.png)

labels added to the project, cc: @FedericoEsparza

**Comment by FedericoEsparza** [comment]
Thanks, @brotich  
I like the additional descriptions. 😁
I'll move this to done!
