### ISSUE TITLE
Michael, where are you?

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/av-dashboard#35]
Why do we have 2 places where we config the database environment variables? alembic.ini vs config.py
 
Can we consolidate this so that it's not a recipe for disaster?

**Comment by FedericoEsparza** [comment]
@mtc2013 I hope you're feeling better. Could you give me admin access to the repo, please, so I can merge PRs?

**Comment by mtc2013** [comment]
so @FedericoEsparza the alembic is like rails migrate but it needs to be told how to find the db in a specific way.  and config.py in the instance folder is for flask environmental configuration which is just the db in this case

**Comment by FedericoEsparza** [comment]
Thanks, @mtc2013 . I was asking for a friend. 😁
