### ISSUE TITLE
setup ci

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/av-dashboard#4]
for instance, travis or semaphoreci

**Comment by Krafty-Coder** [comment]
Would love to work on this one as my first contribution to the project

**Comment by mtc2013** [comment]
@Krafty-Coder you should team up with @brotich who is also working on this ticket

**Comment by Krafty-Coder** [comment]
Which python version is this project written in? 3.5, 3.6?? @mtc2013 @brotich

**Comment by brotich** [comment]
@Krafty-Coder My recommendation is to work with this in `Python3.6`.

**Comment by Krafty-Coder** [comment]
Thanks @brotich, are you doing it or shoul I create a PR?

**Comment by brotich** [comment]
@Krafty-Coder Go ahead and create a PR and tag me for a review. Btw which CI are you looking at implementing for this project...

**Comment by Krafty-Coder** [comment]
Travis ci @brotich

**Comment by brotich** [comment]
@Krafty-Coder awesome...looking forward for the PR....thanks for taking this on.

**Comment by brotich** [comment]
Followup task to be done:
- [ ] enable build for Travis for the project under the AgileVentures
- [ ] update the badge on the ReadMe to point from `Krafty-Coder ` to `AgileVentures` for the travis build above 

cc: @mtc2013 @Krafty-Coder

**Comment by brotich** [comment]
@mtc2013 This can be closed now as the builds are running
