### ISSUE TITLE
Update TravisCI badges to use the AgileVentures account

### ISSUE THREAD

**Issue by brotich** [AgileVentures/av-dashboard#6]
Based on the work done in https://github.com/AgileVentures/av-dashboard/issues/4 to set up travisCI, the badges on the repo point to a developers travis account. This should be update to point to the account under the organisation

## Tasks
- [x] activate travisCI for the repo to enable build to run
- [x] update the badge URL to point to the travis account above. 
         - builds located at: https://travis-ci.org/AgileVentures/av-dashboard

**Comment by brotich** [comment]
@mtc2013 Tagging you on this. I believe to may have the rights to enable the travis builds for this repo

**Comment by mtc2013** [comment]
@brotich i believe i have now authorized the AV account for  av-dashboard travis

**Comment by brotich** [comment]
@mtc2013 Thanks for the update.
@Krafty-Coder, go ahead and update the travis badges to point to https://travis-ci.org/AgileVentures/av-dashboard.

**Comment by Krafty-Coder** [comment]
@brotich I think the PR is ready
