### ISSUE TITLE
start pulling data from a database

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/av-dashboard#9]
like a clone of production db on wso to start with in av dashboard production

-------------------------------------------------------------------------

1)setup scaffolding to provide default database schema/values for development/testing

**Comment by Krafty-Coder** [comment]
Do we have a database already on production for this @mtc2013

**Comment by mtc2013** [comment]
@Krafty-Coder no

**Comment by mtc2013** [comment]
Fixed
